import { describe, expect, it, vi } from 'vitest'
import { canonicalJson, createActivityV1, createSealV1, DshStorageDomainSealedFacts, genesisSealHash } from '../../src/index.js'
import type { SealV1, StorageDomainFacility } from '../../src/index.js'
function fake() { const tables = new Map<string, Map<string, unknown>>(); const table = (n: string) => { let t = tables.get(n); if (!t) { t = new Map(); tables.set(n, t) }; return { get: (k: string) => t!.get(k), put: async (k: string, v: unknown) => { t!.set(k, v) } } }; const close = vi.fn(async () => {}); return { tables, close, facility: { open: async () => ({ table, close }) } as StorageDomainFacility } }
function pair(seq = 116, previous = genesisSealHash('life')) { const seal = createSealV1({ lifecycleFingerprint: 'life', sourceSeq: seq, request: { eventSeq: seq, eventType: 'tool/call', callId: 'call-' + seq, toolName: 'bash' }, approvalAsked: { eventSeq: seq + 1, requestId: 'ask-' + seq }, actionHash: 'sha256:' + 'a'.repeat(64), projectorId: 'projector', catalog: { epoch: seq === 116 ? 0 : 1, headerEventSeq: 0, commitment: 'catalog' }, wireSchemaFingerprint: 'sha256:' + 'b'.repeat(64), result: { eventSeq: seq + 2, status: 'completed' }, epochBoundary: { previousEpoch: seq === 116 ? null : 0, changed: seq !== 116 }, previousSealHash: previous }); return { seal, activity: createActivityV1({ lifecycleFingerprint: 'life', sourceSeq: seq, occurredAt: seq, classification: 'write', targetSummary: 'file', resultCategory: 'completed', sourceSealHash: seal.sealHash }) } }
function tableKey(f: ReturnType<typeof fake>, table: string): string { return [...f.tables.get(table)!.keys()][0]! }
function reseal(original: SealV1, changes: Partial<SealV1>): SealV1 { const { version: _version, sealHash: _sealHash, canonical: _canonical, ...input } = { ...original, ...changes }; return createSealV1(input) }
function replaceTipKeys(f: ReturnType<typeof fake>, keys: string[]) { const t = f.tables.get('chain_tips')!, key = tableKey(f, 'chain_tips'), raw = t.get(key) as { lifecycleFingerprint: string; tipHash: string }; const p = { version: 1 as const, lifecycleFingerprint: raw.lifecycleFingerprint, keys, tipHash: raw.tipHash }; t.set(key, { ...p, canonical: canonicalJson(p) }) }
describe('DshStorageDomainSealedFacts', () => {
 it('accepts sparse source event sequences and a cross-epoch continuation', async () => { const f = fake(), s = new DshStorageDomainSealedFacts(f.facility), a = pair(116), b = pair(50615, a.seal.sealHash); await expect(s.append(a.seal, a.activity)).resolves.toBe('created'); await expect(s.append(b.seal, b.activity)).resolves.toBe('created'); expect((await s.read('life'))?.map(row => row.seal.sourceSeq)).toEqual([116, 50615]) })
 it('creates once and rejects a self-consistent conflicting same-key seal', async () => { const f = fake(), s = new DshStorageDomainSealedFacts(f.facility), p = pair(); await s.append(p.seal, p.activity); const conflict = reseal(p.seal, { projectorId: 'other' }); const { version: _version, canonical: _canonical, ...activityInput } = p.activity; const activity = createActivityV1({ ...activityInput, sourceSealHash: conflict.sealHash }); await expect(s.append(conflict, activity)).resolves.toBe('conflict') })
 it('rejects a recomputed first-row tamper through the successor link', async () => { const f = fake(), s = new DshStorageDomainSealedFacts(f.facility), a = pair(), b = pair(50615, a.seal.sealHash); await s.append(a.seal, a.activity); await s.append(b.seal, b.activity); const changed = reseal(a.seal, { projectorId: 'changed' }); f.tables.get('seals')!.set(tableKey(f, 'seals'), changed); await expect(s.read('life')).resolves.toBeUndefined() })
 it('rejects a broken previous hash, duplicate keys, holes, and out-of-order keys', async () => { const f = fake(), s = new DshStorageDomainSealedFacts(f.facility), a = pair(), b = pair(50615, a.seal.sealHash); await s.append(a.seal, a.activity); await s.append(b.seal, b.activity); const selfConsistentBroken = reseal(b.seal, { previousSealHash: 'sha256:' + 'c'.repeat(64) }); const secondKey = [...f.tables.get('seals')!.keys()][1]!; f.tables.get('seals')!.set(secondKey, selfConsistentBroken); const activityKey = [...f.tables.get('activity')!.keys()][1]!; const { version: _version, canonical: _canonical, ...activityInput } = b.activity; f.tables.get('activity')!.set(activityKey, createActivityV1({ ...activityInput, sourceSealHash: selfConsistentBroken.sealHash })); await expect(s.read('life')).resolves.toBeUndefined(); f.tables.get('seals')!.set(secondKey, b.seal); f.tables.get('activity')!.set(activityKey, b.activity); const descending = pair(100, b.seal.sealHash); await expect(s.append(descending.seal, descending.activity)).resolves.toBe('conflict'); const seals = f.tables.get('seals')!, first = tableKey(f, 'seals'); seals.set(first, { ...a.seal, previousSealHash: 'sha256:' + 'c'.repeat(64) }); await expect(s.read('life')).resolves.toBeUndefined(); seals.set(first, a.seal); const keys = [...seals.keys()]; replaceTipKeys(f, [keys[0]!, keys[0]!]); await expect(s.read('life')).resolves.toBeUndefined(); replaceTipKeys(f, [keys[1]!]); await expect(s.read('life')).resolves.toBeUndefined(); replaceTipKeys(f, [keys[1]!, keys[0]!]); await expect(s.read('life')).resolves.toBeUndefined() })
 it('repairs an identical orphan seal after a partial write', async () => { const f = fake(), s = new DshStorageDomainSealedFacts(f.facility), p = pair(); f.tables.set('seals', new Map([[tableKey as unknown as string, p.seal]])); const seals = f.tables.get('seals')!; seals.clear(); const key = 'l1_' + 'x'; void key; // create the exact derived key by letting a failing activity put leave the seal.
  const original = f.facility.open; let fail = true; f.facility.open = async spec => { const h = await original(spec); return { ...h, table: name => { const t = h.table(name); return name === 'activity' ? { ...t, put: async (k, v) => { if (fail) { fail = false; throw new Error('crash') }; await t.put(k, v) } } : t } } }; const crashing = new DshStorageDomainSealedFacts(f.facility); await expect(crashing.append(p.seal, p.activity)).resolves.toBe('unavailable'); const recovered = new DshStorageDomainSealedFacts(f.facility); await expect(recovered.append(p.seal, p.activity)).resolves.toBe('identical'); expect(await recovered.read('life')).toHaveLength(1) })
 it('treats unknown rows as missing and drains safely', async () => { const f = fake(), s = new DshStorageDomainSealedFacts(f.facility), p = pair(); await s.append(p.seal, p.activity); f.tables.get('seals')!.set(tableKey(f, 'seals'), { version: 99 }); await expect(s.read('life')).resolves.toBeUndefined(); await s.drain(); await expect(s.append(p.seal, p.activity)).resolves.toBe('unavailable'); expect(f.close).toHaveBeenCalledOnce() })
})
