import { describe, expect, it, vi } from 'vitest'
import { createActivityV1, createSealV1, DshStorageDomainSealedFacts, genesisSealHash } from '../../src/index.js'
import type { StorageDomainFacility } from '../../src/index.js'
function fake() { const tables = new Map<string, Map<string, unknown>>(); const table = (n:string) => { let t=tables.get(n); if(!t){t=new Map();tables.set(n,t)} return {get:(k:string)=>t!.get(k),put:async(k:string,v:unknown)=>{t!.set(k,v)}} }; const close=vi.fn(async()=>{}); return {tables,close,facility:{open:async()=>({table,close})} as StorageDomainFacility} }
function pair(seq=0, previous=genesisSealHash('life')) { const seal=createSealV1({lifecycleFingerprint:'life',sourceSeq:seq,request:{eventSeq:seq,eventType:'tool/call',callId:'call-'+seq,toolName:'bash'},approvalAsked:{eventSeq:seq+1,requestId:'ask-'+seq},actionHash:'sha256:'+'a'.repeat(64),projectorId:'projector',catalog:{epoch:seq?1:0,headerEventSeq:0,commitment:'catalog'},wireSchemaFingerprint:'sha256:'+'b'.repeat(64),result:{eventSeq:seq+2,status:'completed'},epochBoundary:{previousEpoch:seq?0:null,changed:!!seq},previousSealHash:previous}); return {seal,activity:createActivityV1({lifecycleFingerprint:'life',sourceSeq:seq,occurredAt:seq,classification:'write',targetSummary:'file',resultCategory:'completed',sourceSealHash:seal.sealHash})} }
describe('DshStorageDomainSealedFacts',()=>{
 it('creates once and detects conflicting same-key canonical payload',async()=>{const f=fake(),s=new DshStorageDomainSealedFacts(f.facility),p=pair();await expect(s.append(p.seal,p.activity)).resolves.toBe('created');await expect(s.append(p.seal,p.activity)).resolves.toBe('identical');const bad={...p.seal,projectorId:'other'};await expect(s.append(bad,p.activity)).resolves.toBe('conflict')})
 it('validates genesis-to-tip, epoch continuation, and restart recovery',async()=>{const f=fake(),s=new DshStorageDomainSealedFacts(f.facility),a=pair(),b=pair(1,a.seal.sealHash);await s.append(a.seal,a.activity);await s.append(b.seal,b.activity);expect((await s.read('life'))).toHaveLength(2);const restart=new DshStorageDomainSealedFacts(f.facility);expect((await restart.read('life'))).toHaveLength(2)})
 it('treats holes, tampering, and polluted rows as missing',async()=>{const f=fake(),s=new DshStorageDomainSealedFacts(f.facility),a=pair();await s.append(a.seal,a.activity);const key=[...f.tables.get('seals')!.keys()][0]!;f.tables.get('seals')!.set(key,{version:99});await expect(s.read('life')).resolves.toBeUndefined()})
 it('drains then closes and rejects new writes',async()=>{const f=fake(),s=new DshStorageDomainSealedFacts(f.facility);await s.drain();const p=pair();await expect(s.append(p.seal,p.activity)).resolves.toBe('unavailable');expect(f.close).toHaveBeenCalledOnce()})
})
